config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists

  root 'artists#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @author = Artist.find(params[:id])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @artist.image = params[:file]
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :img, :image)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @song.image = params[:file]
    @artists = Artist.all
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist_id, :year, :album, :img, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <p>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </p>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
  <br/>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<div class="name"><h1>Listing Artists</h1></div>

<% @artists.each do |artist| %>
    <div class="name"><h3><%= link_to "#{artist.name}", artist %></h3></div>
    <div class="thumbnail"><%= link_to image_tag(artist.image.url), artist %></div>
    <!-- <td><%= link_to 'Show', artist %></td> -->
    <!-- <td><%= link_to 'Edit', edit_artist_path(artist) %></td> -->
    <!-- <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
<% end %>

<%= link_to 'New Artist', new_artist_path, class: "btn btn-default btn-lg" %> |
<%= link_to 'All Songs', songs_path, class: "btn btn-default btn-lg" %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <div class="name">
    <h1><%= @artist.name %></h1>
  </div>
</p>

<p>
  <%= image_tag(@artist.image.url, class: "artist-img") %>
</p>

<div class="name">
  <h2>Songs</h2>
</div>

<% @artist.songs.each do |song| %>
  <div class="name">
    <p>Name: <%= link_to song.name, song %><p>
    <p>Album: <%= song.album %>, <%= song.year %><p>
  </div>
  <div class="thumbnail">
    <%= image_tag(song.image.url) %>
  </div>
<%end%>

<%= link_to 'Edit Artist', edit_artist_path(@artist), class: "btn btn-default btn-lg" %> |
<%= link_to 'New Song', new_song_path, class: "btn btn-default btn-lg" %>
<br/>
<div class="name"><%= link_to 'Back', artists_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicPlease</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.select :artist_id, options_from_collection_for_select(@artists, "id", "name", selected: @song.artist_id) %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <p>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </p>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
  <br/>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Year</th>
      <th>Album</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.name, song %></td>
        <td><%= song.artist.name %></td>
        <td><%= song.year %></td>
        <td><%= song.album %></td>
        <td class="thumbnail"><%= link_to image_tag(song.image.url), song %></td>
        <!-- <td><%= link_to 'Show', song %></td> -->
        <!-- <td><%= link_to 'Edit', edit_song_path(song) %></td> -->
        <!-- <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path, class: "btn btn-default btn-lg" %> |
<%= link_to 'Back to Artists', artists_path, class: "btn btn-default btn-lg" %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Song</h1>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @song.year %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <%= image_tag(@song.image.url, class: "thumbnail right") %>
</p>

<%= link_to 'Back', artist_path(@song.artist.id), class: "btn btn-default btn-lg" %>
<%= link_to 'Edit', edit_song_path(@song), class: "btn btn-default btn-lg" %>
</div>